//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mbc.Pcs.Net.Command {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CommandResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommandResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mbc.Pcs.Net.Command.CommandResources", typeof(CommandResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The command was cancelled by user request..
        /// </summary>
        internal static string ERR_CommandCanceled {
            get {
                return ResourceManager.GetString("ERR_CommandCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command is already running and is therefore locked..
        /// </summary>
        internal static string ERR_ExecutionBehaviorCommandLocked {
            get {
                return ResourceManager.GetString("ERR_ExecutionBehaviorCommandLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing input variables on the PLC implementation: &apos;{0}&apos;.
        /// </summary>
        internal static string ERR_InputVariablesMissing {
            get {
                return ResourceManager.GetString("ERR_InputVariablesMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADS-Client is not connected..
        /// </summary>
        internal static string ERR_NotConnected {
            get {
                return ResourceManager.GetString("ERR_NotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing output variables on the PLC implementation: &apos;{0}&apos;.
        /// </summary>
        internal static string ERR_OutputVariablesMissing {
            get {
                return ResourceManager.GetString("ERR_OutputVariablesMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The command execution failed with resultCode &apos;{0}&apos;..
        /// </summary>
        internal static string ERR_ResultCode {
            get {
                return ResourceManager.GetString("ERR_ResultCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The command was cancelled..
        /// </summary>
        internal static string ERR_ResultCode_3 {
            get {
                return ResourceManager.GetString("ERR_ResultCode_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The command timed out after {Timeout.Seconds} [s]..
        /// </summary>
        internal static string ERR_TimeOut {
            get {
                return ResourceManager.GetString("ERR_TimeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled ADS-Datatype &apos;{0}&apos;. Please extend implementation!.
        /// </summary>
        internal static string ERR_UnknownAdsType {
            get {
                return ResourceManager.GetString("ERR_UnknownAdsType", resourceCulture);
            }
        }
    }
}
