<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <StartupObject>Profiling.Program</StartupObject>
    <IsPackable>false</IsPackable>
    <CodeAnalysisRuleSet>$(MSBuildProjectDirectory)\..\..\Build\Mbc.CodeAnalysis.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Mbc.Pcs.Net.DataRecorder\Mbc.Pcs.Net.DataRecorder.csproj" />
  </ItemGroup>

</Project>
