<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.6">
  <POU Name="MAIN" Id="{12ac386e-9f2f-456d-9446-322109fb7ee0}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	counter				: UINT;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[counter := counter + 1;

Commands.fbStartCommand1.bEnabled := TRUE;

PRG_Commands();
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>