<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <StartupObject>Cli.Program</StartupObject>
    <IsPackable>false</IsPackable>
    <CodeAnalysisRuleSet>$(MSBuildProjectDirectory)\..\..\Build\Mbc.CodeAnalysis.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging" Version="10.*" />
    <PackageReference Include="NLog.Web.AspNetCore" Version="4.*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Mbc.Pcs.Net.Command\Mbc.Pcs.Net.Command.csproj" />
  </ItemGroup>

</Project>
